#!/usr/bin/bash

if [[ ${dryrun} == true ]]; then
  cmd="echo "
else
  cmd=""
fi

source utils.sh

if [[ $(uname -n) == "archiso" ]]; then
  mountpoint=$(grep mountpoint user_configuration.json | cut -f 4 -d '"')
  echo "mountpoint=${mountpoint}"
  CMD="${cmd} arch-chroot ${mountpoint} "
else
  mountpoint=""
  CMD=${cmd}
fi

${CMD} pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
${CMD} pacman-key --lsign-key 3056513887B78AEB
${CMD} pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

${cmd} echo "[chaotic-aur]" >>"${mountpoint}/etc/pacman.conf"
${cmd} echo "Include = /etc/pacman.d/chaotic-mirrorlist" >>"${mountpoint}/etc/pacman.conf"

${CMD} pacman -Syyu --needed --noconfirm

box_me "Install arch specific chaotic packages"
packages="${packages} $(./info.py chaotic)"
packages="${packages} $(./info.py browsers)"
# packages="${packages} $(./info.py myfonts)"
${CMD} pacman -S --needed --noconfirm ${packages}
