#!/usr/bin/env bash

if [[ ${#} -ne 1 ]]; then
  printf "You must enter disk with the partitions you want to initialize\n"
  lsblk
  exit 1
fi

disk=${1}

while read -u 7 name partlabel rest; do
  case ${partlabel} in
    EFI|EPS)
      read -u 2 -p "Do you want to reformat /dev/${name} [YES/NO]-> " ans
      if [[ ${ans^^} == "YES" ]]; then
        mkfs.vfat -F32 -n EFI /dev/disk/by-partlabel/EFI
      fi
      ;;
    SWAP|swap)
      swapoff --all
      mkswap /dev/disk/by-partlabel/swap
      swapon
      ;;
    archlinux)
      read -u 2 -p "Do you want to reformat /dev/${name} [YES/NO]-> " ans
      if [[ ${ans^^} == "YES" ]]; then
        #TODO: add encryption of root volume
        rootdisk=/dev/disk/by-partlabel/archlinux

         mkfs.btrfs -f -L archlinux ${rootdisk}
         mount --mkdir ${rootdisk} /mnt/archinstall

         btrfs subvolume create /mnt/archinstall/@
         btrfs subvolume create /mnt/archinstall/@home
         btrfs subvolume create /mnt/archinstall/@root
         btrfs subvolume create /mnt/archinstall/@srv
         btrfs subvolume create /mnt/archinstall/@cache
         btrfs subvolume create /mnt/archinstall/@log
         btrfs subvolume create /mnt/archinstall/@tmp
         btrfs subvolume create /mnt/archinstall/@images
         btrfs subvolume create /mnt/archinstall/@.snapshots
      fi
      ;;
    *)
      printf "${partlabel} not used during installation\n"
      ;;
  esac
 done 7<<<$(lsblk -o NAME,PARTLABEL ${disk} \
   | grep -E "${disk##*/}[0-9]" \
   | sed -e s'/..//'
 )


umount -R /mnt/archinstall

mount --mkdir --options subvol=/@,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall
mount --mkdir --options subvol=/@home,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/home
mount --mkdir --options subvol=/@.snapshots,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/.snapshots
mount --mkdir --options subvol=/@root,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/root
mount --mkdir --options subvol=/@srv,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/srv
mount --mkdir --options subvol=/@cache,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/var/cache
mount --mkdir --options subvol=/@log,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/var/log
mount --mkdir --options subvol=/@tmp,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/var/tmp
mount --mkdir --options subvol=/@images,defaults,noatime,compress=zstd ${rootdisk} /mnt/archinstall/var/lib/libvirt/images

mount --mkdir --options defaults /dev/disk/by-partlabel/EFI /mnt/archinstall/boot/efi


