#!/usr/bin/env bash

if [[ ${dryrun} == true ]]; then
  cmd="echo "
else
  cmd=""
fi

source utils.sh

if [[ $(uname -n) == "archiso" ]]; then
  mountpoint=$(grep mountpoint user_configuration.json | cut -f 4 -d '"')
  echo "mountpoint=${mountpoint}"
  CMD="${cmd} arch-chroot ${mountpoint} "
else
  mountpoint=""
  CMD=${cmd}
fi

${cmd} sudo timedatectl set-timezone America/Los_Angeles
${cmd} sudo timedatectl set-ntp true

${cmd} sudo ./snapper_install

box_me "Install arch specific post-install packages"

packages=(git intel-ucode)
packages+=("$(./info.py browsers)")
packages+=("$(./info.py backrestore)")
packages+=("$(./info.py mymisc)")
packages+=("$(./info.py office)")
packages+=("$(./info.py jakoolit)")
packages+=("$(./info.py virtualization)")
echo ${packages[@]}
read -p "waiting on review" ans
${cmd} sudo pacman -Syu --needed --noconfirm ${packages[@]}

box_me "Setup JaKooLit hyprland"
${cmd} git clone --depth=1 https://github.com/JaKooLit/Arch-Hyprland.git ~/Arch-Hyprland
${cmd} cd ~/Arch-Hyprland
${cmd} chmod +x install.sh
${cmd} ./install.sh
# ${cmd} sh <(curl -L https://raw.githubusercontent.com/JaKooLit/Arch-Hyprland/main/auto-install.sh)
